"""One import point for the Qt binding.

PySide6 is the distributable runtime. The small PyQt6 fallback preserves
development/test usability on a Mac that already has only that binding; it is
never declared as a production or packaged dependency.
"""

from __future__ import annotations

try:  # pragma: no cover - exercised in packaged PySide6 releases
    from PySide6.QtCore import (
        QEasingCurve,
        QEvent,
        QObject,
        QPoint,
        QRect,
        QRectF,
        QSize,
        Qt,
        QThread,
        QTimer,
        QUrl,
        QVariantAnimation,
        Signal,
    )
    from PySide6.QtGui import (
        QAction,
        QBrush,
        QColor,
        QCursor,
        QDesktopServices,
        QFont,
        QFontDatabase,
        QFontMetrics,
        QGuiApplication,
        QKeySequence,
        QLinearGradient,
        QPainter,
        QPainterPath,
        QPalette,
        QPen,
        QPixmap,
        QShortcut,
        QTextCursor,
        QTextOption,
        QTransform,
    )
    from PySide6.QtSvg import QSvgRenderer
    from PySide6.QtWidgets import (
        QApplication,
        QButtonGroup,
        QCheckBox,
        QComboBox,
        QDialog,
        QFileDialog,
        QFrame,
        QGraphicsDropShadowEffect,
        QGraphicsPixmapItem,
        QGraphicsRectItem,
        QGraphicsScene,
        QGraphicsView,
        QGridLayout,
        QHBoxLayout,
        QLabel,
        QLineEdit,
        QLayout,
        QMainWindow,
        QMessageBox,
        QPlainTextEdit,
        QPushButton,
        QScrollArea,
        QSizePolicy,
        QStackedWidget,
        QStyle,
        QTextBrowser,
        QTextEdit,
        QToolButton,
        QVBoxLayout,
        QWidget,
    )
except ImportError:  # pragma: no cover - local developer fallback only
    from PyQt6.QtCore import (  # type: ignore[no-redef]
        QEasingCurve,
        QEvent,
        QObject,
        QPoint,
        QRect,
        QRectF,
        QSize,
        Qt,
        QThread,
        QTimer,
        QUrl,
        QVariantAnimation,
    )
    from PyQt6.QtCore import pyqtSignal as Signal  # type: ignore[no-redef]
    from PyQt6.QtGui import (  # type: ignore[no-redef]
        QAction,
        QBrush,
        QColor,
        QCursor,
        QDesktopServices,
        QFont,
        QFontDatabase,
        QFontMetrics,
        QGuiApplication,
        QKeySequence,
        QLinearGradient,
        QPainter,
        QPainterPath,
        QPalette,
        QPen,
        QPixmap,
        QShortcut,
        QTextCursor,
        QTextOption,
        QTransform,
    )
    from PyQt6.QtSvg import QSvgRenderer  # type: ignore[no-redef]
    from PyQt6.QtWidgets import (  # type: ignore[no-redef]
        QApplication,
        QButtonGroup,
        QCheckBox,
        QComboBox,
        QDialog,
        QFileDialog,
        QFrame,
        QGraphicsDropShadowEffect,
        QGraphicsPixmapItem,
        QGraphicsRectItem,
        QGraphicsScene,
        QGraphicsView,
        QGridLayout,
        QHBoxLayout,
        QLabel,
        QLineEdit,
        QLayout,
        QMainWindow,
        QMessageBox,
        QPlainTextEdit,
        QPushButton,
        QScrollArea,
        QSizePolicy,
        QStackedWidget,
        QStyle,
        QTextBrowser,
        QTextEdit,
        QToolButton,
        QVBoxLayout,
        QWidget,
    )

__all__ = [name for name in dir() if name[0] == "Q" or name == "Signal" or name == "Qt"]
